# Wiki
wiki_name: Minetest JP Wiki

# Jekyll
source       : ./wiki
data_dir     : ./wiki/data
destination  : ./_site
layouts_dir  : ./_layouts
includes_dir : ./_includes
markdown     : kramdown
exclude      : ["Gemfile"]

defaults :
  -
    scope:
      path: "wiki"
    values:
      layout: "default"
      permalink: /:basename/

sass:
  style: compressed
  
#gems:
#  - jekyll-sitemap
