repository: minetest-jp/wiki
url: https://minetest-jp.github.io/wiki
title: Minetest JP Wiki
google_site_verification: SzmyhmFa1r6eafWLqLct1hOKj-Awxn0JH8r0U4PUCyc
lang: ja_JP
logo: "img/icon.png"
author: Minetest-JP Team
publisher: Minetest-JP Team
media-desktop: "all and (min-width: 768px)"
media-mobile: "not all and (min-width: 768px)"
exclude: ["README.md", "CONTRIBUTING.md", "imgs/LICENSE.txt", "vendor"]

minetest:
  # Minetestの最新バージョン
  # Windowsのダウンロードリンクもこれに依存します
  latest_version: "5.0.1"

wiki:
  img_dir: "imgs"
  theme_color: "#fff" # モバイル版Chromeのタブ色

kramdown:
  input: "GFM"
  html_to_native: true
  header_offset: 1 # Markdownの"#"を<h2>として扱う

sass:
  style: "compressed"

compress_html:
  comments: all

collections:
  pages:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      date: 2018-1-1
      layout: "default"
      seo:
        type: "WebSite"
      image:
        path: "img/icon.png"
        width: 600
        height: 603

plugins:
  - "jekyll-sitemap" # サイトマップ生成
