# Wiki
wiki_name       : "Minetest JP Wiki"
wiki_images_dir : "./wiki/images"

# Jekyll
source       : "./wiki"
data_dir     : "./wiki/data"
destination  : "./_site"
layouts_dir  : "./_layouts"
includes_dir : "./_includes"
markdown     : "kramdown"
exclude      : ["Gemfile"]

defaults:
 -
  scope:
    path: "wiki"
  values:
    layout: "default"
    permalink: ":basename"

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed
  
#gems:
#  - jekyll-sitemap
