# Wiki
wiki_name: "Minetest JP Wiki"

# Jekyll
source       : "./wiki"
data_dir     : "./wiki/data"
destination  : "./_site"
layouts_dir  : "./_layouts"
includes_dir : "./_includes"
permalink    : "/:basename"
layout       : "default"
markdown     : "kramdown"
exclude      : ["Gemfile"]
sass:
  style: compressed
  
#gems:
#  - jekyll-sitemap
