wiki_name: Minetest JP Wiki

source: ./pages
data_dir: ./pages/data
destination: ./_site
layouts_dir: ./_layouts
includes_dir: ./_includes
#include: ["css"]
markdown: kramdown
sass:
  style: compressed
#gems:
#  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
